name: Testing

on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - run: mkdir -p path/to/artifact
    - run: echo hello > path/to/artifact/world.txt
    - uses: actions/upload-artifact@v2
      env:
          name: "lol"
          path: path/to/artifact/world.txt
    
